### ISSUE TITLE
 MySQL 8 Support

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/wg-build-test-release#137]
[Data Working Group: 2022-01-27 Meeting & MySQL Upgrade Path Proposal](https://discuss.openedx.org/t/data-working-group-2022-01-27-meeting-mysql-upgrade-path-proposal/6527)

openedx/platform-roadmap#119 - It looks like MySQL 8 will be supported for Nutmeg.

**Comment by jfavellar90** [comment]
According to the most recent [update](https://github.com/openedx/platform-roadmap/issues/119#issuecomment-1068548572) regarding the update, MySQL 8.0 is still a goal for Nutmeg. It seems Nutmeg will be compatible with Mysql 5.7, so it's up to us to decide if we proceed with the update to 8.0.

**Comment by NeOneSoft** [comment]
Hi @jfavellar90!! according to this [PR](https://github.com/overhangio/tutor/pull/623l) seems that Nutmeg compatibility with MySQL 5.7 and MySQL 8.0 was merged. Do you think that we need something else? Thank you so much

**Comment by NeOneSoft** [comment]
Hi mi amigo @jfavellar90. Do we have any update here?. Please let me know if I can help you with this!!!

**Comment by throwaway-a** [comment]
Has the mysql support added unicode support in a way that will fix the issue with emojis in titles as mentioned [here](https://discuss.openedx.org/t/emoji-in-subsection-title-not-supported-since-nutmeg/7856/3) and [here](https://discuss.openedx.org/t/nutmeg-upgrade-outlines-py-openedx-core-djangoapps-content-learning-sequences-models-learningcontext-doesnotexist-learningcontext-matching-query-does-not-exist/7892/30) and [here](https://discuss.openedx.org/t/upgrading-mysql-charset-to-utf8mb4/7927/3), so that people don't need to do anything special to support it out of the box?

**Comment by mariajgrimaldi** [comment]
Hello @regisb: correct me if I'm wrong, but is the palm release test instance going to use Mysql 8? Or are there other issues to be resolved first?

**Comment by regisb** [comment]
I would like Palm (Tutor 16.0.0) to run on MySQL 8.0, so yes I expect that the test instance is going to use that version. I have not yet attempted to upgrade but I was told that Open edX supports MySQL 8.0, so I don't expect any major issue. For the record, edX.org still runs 5.7, but only because upgrading would cause too much downtime.

**Comment by jalondonot** [comment]
@regisb, I guess we could mark this as done?

**Comment by regisb** [comment]
Yes.

**Comment by regisb** [comment]
1. Work in a temporary project root: `export TUTOR_ROOT=/path/to/some/tmp/file`
2. Install tutor (Olive) from pypi: `pip install tutor`
3. Launch an Olive platform: `tutor local launch`
4. Check that the platform works
5. Install tutor v16 (Palm): `pip install git+https://github.com/overhangio/tutor@palm#egg=tutor`
6. Upgrade: `tutor local launch`
7. Check that it works

**Comment by regisb** [comment]
> If I just don't set the tmp TUTOR_ROOT would the pip and launch commands instead do an upgrade in place? Because that's more what I want to test works (and of course I want to test what's working vs. breaking on my existing classes.)

Yes, this is correct.

> But the fact that it is still referencing /home/ubuntu/tmp_tutor, which is what I set the TUTOR_ROOT to before, makes me think the unsetting of the variable was not enough. 

Right. I suspect that you did not properly unset the variable. Indeed, `unset -f` is only for un-setting functions:

```
$ export POUAC=1
$ unset -f POUAC
$ env | grep POUAC
POUAC=1
$ unset POUAC
$ env | grep POUAC
# nothing, variable was properly unset
```

You should use `unset TUTOR_ROOT` (or open a new shell).

**Comment by regisb** [comment]
`docker-compose` is unsupported starting from June 2023 (that's today!) and replaced by the Compose plugin: https://docs.docker.com/compose/install/
I suggest you upgrade your installation of Docker and Compose.
