### ISSUE TITLE
Bookmark tool is not saving bookmarks

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#270]
Bookmark functionality appears to not be working in Palm demo instance. 

Steps to recreate:
1. Log in as a student user to a published, released course. 
2. Bookmark a page using the 'bookmark this page' button under a unit title.
3. The page will appear as though it has been bookmarked; https://prnt.sc/ruM5FnrswFdA
4. Refresh the page. Note the bookmark has disappeared: https://prnt.sc/WyWEBQtSsDPM
5. Go to the bookmarks page for the course. Note that no bookmarks have been saved: 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1486185/233795080-e7b9b683-3af9-406b-ba99-ca890dd6028b.png">

```[tasklist]
### PRs
- [ ] https://github.com/openedx/frontend-app-learning/pull/1120
```

**Comment by Henrrypg** [comment]
assign me

**Comment by sambapete** [comment]
It's no longer working in Olive.3 according to some recent tests.
See https://discuss.openedx.org/t/olive-bookmarks-failing/10022

**Comment by DeanJayMathew** [comment]
Hi @Henrrypg 

Are you still pursuing this?

**Comment by regisb** [comment]
When we click "bookmark this page", the learning MFE makes a POST to http://apps.local.overhang.io/api/bookmarks/v1/bookmarks/. Of course this page does not exist because there is no MFE running at "/api". So the MFE server does what it usually does when it doesn't know what to do with a request: make an empty 200 response... (don't blame me, this is part of the MFE spec!)

The POST should be made to http://local.overhang.io/api/bookmarks/v1/bookmarks/ (the lms container), and not http://apps.local.overhang.io/... (the mfe container). But I do not understand why this is the case. It does seem like the learning MFE is using the LMS_BASE_URL: https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/course/bookmark/data/api.js

The behaviour in "dev" is interesting. When I click "bookmark this page" a call is made to http://localhost:18000/csrf/api/v1/token instead of http://lms.overhang.io:8000/csrf/api/v1/token. This suggests that the LMS_BASE_URL setting is incorrectly read or defined by the bookmarks tool. 

When I add a breakpoint to the learning MFE I see that the configuration seems to come from build time, not runtime:

![Screenshot from 2023-05-17 13-25-56](https://github.com/openedx/wg-build-test-release/assets/44319/73e73e9b-dbe7-4231-bc5c-19d0048286d5)
![Screenshot from 2023-05-17 13-26-15](https://github.com/openedx/wg-build-test-release/assets/44319/79bb06c2-e79c-4224-b16e-469d38bc27ec)

(apologize the crude debugging, my frontend skills are not that great...)

My interpretation is that the bookmarks tool does not make use of the runtime configuration. How can I confirm this intuition?

**Comment by Henrrypg** [comment]
Hello @DeanJayMathew, i was testing and my first approach was same as @regisb. But i'm having problems with my frontend and MFEs skills to get a solutions for that. I'll unassign me to left it to somebody with more frontend skills and i'll take another task.

**Comment by ghassanmas** [comment]
A propose changes to fix issue, has been summited at: 
 - openedx/frontend-app-learning/pull/1120

**Comment by regisb** [comment]
Here's the backport PR: https://github.com/openedx/frontend-app-learning/pull/1123 Can someone please review and merge?
