### ISSUE TITLE
[Quince Testing] <TC_AUTHOR_133>: <Course still showing in catalog page even "none" property set in >

### ISSUE THREAD

**Issue by Faisalarbisoft** [openedx/wg-build-test-release#330]
### Release

Quince

### Expected behavior

Studio Advance settings, "Course Visibility In Catalog" defines when "none" value is set then course should not show in catalog and not allows the access to an about page.

### Actual behavior

Course is still displaying in the catalog even "none" value is set against "Course Visibility In Catalog"

### Steps to reproduce

1. Go to studio select any course and go to its Advanced Settings, set the value of "Course Visibility In Catalog" to "none" and save it
2. Go to Lms and check the course catalog page.

### Additional information

<img width="936" alt="Screenshot 2023-11-23 at 4 03 26 PM" src="https://github.com/openedx/wg-build-test-release/assets/151823381/ef8416e5-0f72-4b8d-add9-9c6c4e4a4854">

<img width="1496" alt="Screenshot 2023-11-23 at 4 07 20 PM" src="https://github.com/openedx/wg-build-test-release/assets/151823381/4d7f10b7-3982-4a3f-93bb-6dcf26bfb58e">

**Comment by Faisalarbisoft** [comment]
label: quince testing

**Comment by mariajgrimaldi** [comment]
@Faisalarbisoft: I found a similar issue reported a while ago that's worth reading: https://github.com/openedx/wg-build-test-release/issues/164

The comments say that the /courses page does not refer to the _catalog_and that the setting in advanced settings does not affect the visibility there. So, technically, this is not failing.

I'll tag @ghassanmas and @regisb since they were around by the time of the first report.

**Comment by regisb** [comment]
To the best of my recollection, this is not a bug but a feature that is implemented in a very confusing way. Setting the catalogue visibility as "none" is not meant to affect how the courses are displayed in the `/courses` page. But I think that we should change that behaviour, because it's really not what the user would expect.

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  thanks for pointing out. I have missed this use case and test with "both" only. Let me retest.

**Comment by mariajgrimaldi** [comment]
@jmakowski1123: A few months ago, we discussed this issue in the BTR WG, and the consensus was to change the strategy we've been using until now and involve the product WG in defining what this feature actually is. Can you confirm that the product WG will take a look at this feature? Let me know whether I remember it correctly. Thanks!

**Comment by regisb** [comment]
I opened a pull request to fix this issue in the most simple way: https://github.com/openedx/edx-platform/pull/35646
@jmakowski1123 Do you think this warrants a product proposal? My opinion is that this PR fixes an obvious bug, given that the current behaviour is surprising for all users. 
Cc @sarina with whom I just discussed this issue by email.

**Comment by ghassanmas** [comment]
Also there is PR  https://github.com/openedx/edx-platform/pull/35372, which related to the one above. 
The issue is that course visbility is none for a course and learner who alrady enrolled try to view course outline it will not work.

**Comment by sarina** [comment]
Hi @regisb - I think this is a bugfix, but I'm checking on my side.

@ghassanmas I left a comment on your PR, let's discuss that issue on your PR rather on this issue.
