### ISSUE TITLE
[LMS/Studio] <TC_AUTHOR_141>: <Signature image is not showing on preview certificate>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#332]
### Release

quince

### Expected behavior

The signature image should show when user click on preview certificate button.

### Actual behavior

The signature image is not showing on the preview certificate.

### Steps to reproduce

1. Go to studio and setup a certificate against course
2. add a signatury with image and save it
3. click on preview button

### Additional information

Check here : https://quince.demo.edly.io/certificates/course/course-v1:edly+ed100+100?preview=honor

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by mariajgrimaldi** [comment]
I reported this issue a while ago: https://github.com/openedx/wg-build-test-release/issues/177#issuecomment-1124246022

The signature only displays for `verified` course modes, is that the one you used for this test? I tested it out with the verified course mode, and it worked: https://quince.demo.edly.io/certificates/course/course-v1:edX+DemoX+Demo_Course?preview=verified

I'll close this since it's working as expected.
