### ISSUE TITLE
[Test failure] TC_AUTHOR_151: Unlimited attempts cannot be assigned in problems

### ISSUE THREAD

**Issue by BryanttV** [openedx/wg-build-test-release#371]
### Release

Redwood

### Expected behavior

As a course author, I want to set up a problem with unlimited attempts, so that students can submit their answers as many times as they want.

### Actual behavior

As a course author, I cannot assign a problem with unlimited attempts. It happens when you already have a set number of attempts and want to change to unlimited attempts.

### Steps to reproduce

1. From **Studio** create a problem.
2. Configure the problem with a number of attempts, e.g.: `5`, and save.
3. Edit the problem try to assign unlimited attempts, and save
4. The problem continues to have the same number of attempts assigned previously

https://github.com/openedx/wg-build-test-release/assets/64033729/f722b3a2-ed43-4081-ac13-dd84c7008291

### Additional information

It happens in all problems, but it does not happen with the legacy editor.

**Comment by mariajgrimaldi** [comment]
I can confirm this issue is currently happening in the redwood sandbox. Here's what I've found:
- This happens even without publishing the unit
- When selecting unlimited attempts after setting a limited attempts to any number, the request doesn't include the unlimited attempt change:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/860b6da1-f3c0-4545-b06b-dcb6572d5292)
- When changing the number of attempts, it sends the new change accordingly:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/ddfb8577-ed47-47ec-8b8a-a663ec96b75a)

I'll be reporting this in the frontend-lib-content-components repo.

**Comment by mariajgrimaldi** [comment]
The PR taking care of this issue was merged in https://github.com/openedx/frontend-lib-content-components. I asked the maintainers for some guidance on applying those changes to redwood.

**Comment by mariajgrimaldi** [comment]
I can confirm this is working on the redwood sandbox: 

[Screencast from 10-06-24 10:18:40.webm](https://github.com/openedx/wg-build-test-release/assets/64440265/7f447c23-85e4-4de3-ac3e-c322b1f803a0)
