### ISSUE TITLE
[Test failure] <TC_INSTRUCTOR_4>: <Bulk enrol learners doesn't work, email is not received.>

### ISSUE THREAD

**Issue by AntonellaPerrupato** [openedx/wg-build-test-release#405]
### Release

Sumac

### Expected behavior

You should be able to bulk enroll if you check "notify by email", and also, the email should be sent

### Actual behavior

if you check "notify by email" nobody is enroll and neither the email is sent 

### Steps to reproduce

go to instructor tab
membership
add 2 emails
check  auto enroll and  Notify users by email
click on enroll

**Comment by mariajgrimaldi** [comment]
@AntonellaPerrupato: To confirm this is not related to the long-standing email sending issue, can you help us test whether this works with email domains from protonmail?

**Comment by AntonellaPerrupato** [comment]
@mariajgrimaldi Testing and replying ASAP.

**Comment by AntonellaPerrupato** [comment]
adding the screenshot

![image](https://github.com/user-attachments/assets/5d6e7daa-4c04-4929-9f10-38d666db9a5a)
![image](https://github.com/user-attachments/assets/7e70943e-7d9f-44d8-b641-6d6599875e05)

**Comment by mariajgrimaldi** [comment]
@AntonellaPerrupato: yes, according to the documentation before enrolling the user must activate their account: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/manage_live_course/course_enrollment.html#registration-and-enrollment

I'll close this as resolved since it's related to the email-sending issue, not the feature itself. You can reopen it if you think otherwise. Thank you!
