### ISSUE TITLE
[Test failure] TC_LEARNER_17: No "Email Settings" option

### ISSUE THREAD

**Issue by saraburns1** [openedx/wg-build-test-release#412]
### Release

Sumac

### Expected behavior

Kebab menu for enrolled course should show option 'Email Settings'

### Actual behavior

Kebab menu only shows option of 'Unenroll'

### Steps to reproduce

Sign in to your open edX account and enroll for at least one course. Go to Learner Dashboard and click on kebab menu for enrolled course.

### Additional information

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/a229acee-d4fa-4ffc-9309-43be9aab9404">

**Comment by crathbun428** [comment]
@jmakowski1123 - it seems bad that a learner cannot manage their course email settings from the course dashboard. I did a quick search of the docs and a perusal of the sandbox to see if there is another spot where a user can manage their email settings for the course - there didn't seem to be one. If this is the only option, I'd venture that this is a high priority bug since this should be something learners can manage on their end. I've marked this as high priority for now - please let me know if there's anything I've missed.

**Comment by mariajgrimaldi** [comment]
@crathbun428: I suspect this flag was missing when this was tested: https://sumac.demo.edly.io/admin/bulk_email/bulkemailflag/. Thus, course emails were not enabled, and there was no configuration available.

**Comment by mariajgrimaldi** [comment]
@saraburns1: could you test again considering the flag I mentioned above? Let me know!

**Comment by mariajgrimaldi** [comment]
I'm closing this issue since I couldn't reproduce this issue after enabling the bulk email flag. If the issue persists for testers, we can reopen it.
