### ISSUE TITLE
[Test failure] Schedule and Detail Settings Not Retained During Course Export/Import in Sumac Version

### ISSUE THREAD

**Issue by HeliaEnayati** [openedx/wg-build-test-release#416]
### Release

sumac

### Expected behavior

In the Sumac version, when exporting and importing a course, all schedule and detail settings should be imported correctly, as they were in previous versions like Redwood or Quince

### Actual behavior

In the current Sumac version, when a course is exported and then imported, the schedule and detail settings are not retained, unlike in Redwood where they were successfully imported.

### Steps to reproduce

1. Log in to the studio
2. Create or select an existing course and configure its schedule and detail settings.
3. Export the course.
4. Import the exported course as a new course in the Sumac version.
5. Check the schedule and detail settings in the imported course to confirm their status.

**Comment by DonatoBD** [comment]
Hi @HeliaEnayati, thank you very much for your collaboration on the testing. I'm writing to inform you that I've just tested on [the sandbox](https://studio.sumac.demo.edly.io/) and both the exported zip file and the course after the import retain the Schedule & Details settings modified in the original course.

- [Original course](https://apps.sumac.demo.edly.io/authoring/course/course-v1:OpenedX+BTR-416+01/settings/details)
- [Zip generated with the export](https://github.com/user-attachments/files/17835851/course.y0n9s_px.tar.gz)

- [Course where I performed the import](https://apps.sumac.demo.edly.io/authoring/course/course-v1:OpenedX+BTR-416+02/settings/details)

I also tested locally and it worked. If you have a specific case, please let me know, otherwise I will close this issue assuming it was a one-time error that occurred when you performed the test :smiley:

**Comment by crathbun428** [comment]
@mariajgrimaldi - it seems this issue was not replicable according to @DonatoBD? If that's the case, we can close it. @HeliaEnayati - what was the course/ specific scheduling details you saw that weren't pulled over - maybe there was something specific about the course you used to test that we can try to replicate. 

I've marked this as high priority (since the export page says course dates are part of the export) if this issue is in fact replicable.

**Comment by HeliaEnayati** [comment]
Hi @DonatoBD , @AntonellaPerrupato and @crathbun428 
Thank you for your prompt responses and for taking the time to investigate this issue. I appreciate the thorough testing you conducted on both the sandbox and locally.
After reviewing your feedback, I re-tested the process on my end and, like you, was unable to replicate the issue. It seems that the problem may have been an isolated incident or a one-time error during my initial test. I apologize for any confusion this may have caused.
I will continue to monitor this functionality and will reach out if I encounter any further issues. Thank you again for your support and collaboration.

**Comment by mariajgrimaldi** [comment]
Thank you all! I'll be closing this issue since it cannot be replicated.
