### ISSUE TITLE
[Test failure] TC_AUTHOR_36: Broken link in Studio, Course highlight emails, Learn more

### ISSUE THREAD

**Issue by angonz** [openedx/wg-build-test-release#432]
### Release

Sumac

### Expected behavior

Studio, Course highlight emails, Learn more should lead to https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/developing_course/course_sections.html#set-section-highlights-for-highlight-emails

### Actual behavior

It leads to a broken link in https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-sumac.master/developing_course/course_sections.html#set-section-highlights-for-weekly-course-highlight-messages

### Steps to reproduce

Go to Studio, open any course, in the course outline page click on "Learn more" under "Course highlight emails"
![image](https://github.com/user-attachments/assets/fbb5aecf-d665-4a54-bc1e-bea801d00c01)

**Comment by magajh** [comment]
Thank you for the report! I've confirmed that this issue is occurring

Seems like this link is read from an environment variable specific to the Course Authoring MFE that wasn’t set correctly during deployment? For a moment I thought the URL might be hardcoded, but I couldn’t find it anywhere in the code, and it also doesn’t seem to be returned by the MFE config API

@mariajgrimaldi, do you know who we could tag to help confirm this?

**Comment by mariajgrimaldi** [comment]
Thanks for tagging me! 

@magajh: those help URLs come from this API [/api/contentstore/v1/help_urls](https://github.com/openedx/edx-platform/blob/open-release/sumac.master/cms/djangoapps/contentstore/rest_api/v1/views/help_urls.py#L11-L45). From what I could find, the API generates the links depending on what's in [this file](https://github.com/openedx/edx-platform/blob/202d31b17e4a5fe1f51159f4b8158d089c818130/cms/envs/help_tokens.ini#L35-L36) and the release branch.

The help links don't work because the release is not available yet. You can see more details on this issue here: https://github.com/openedx/wg-build-test-release/issues/163

Please, feel free to close this issue since links will work once the release is out.

**Comment by mariajgrimaldi** [comment]
@angonz: Can we make a note of this on the test sheet?

**Comment by angonz** [comment]
Noted!
